#!/bin/bash
#A script for recompiling the wasm application

SOURCEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

make clean
emmake make
make cleanobj
cp teapots.html build
cp ../webGL/webgl-teapots.css build
